<a href="https://colab.research.google.com/github/nityanandkore/6156-ML-Final-Project/blob/main/Final_Project_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!rm 6156-ML-Final-Project
!git clone https://github.com/nityanandkore/6156-ML-Final-Project.git

rm: cannot remove '6156-ML-Final-Project': No such file or directory
Cloning into '6156-ML-Final-Project'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 10 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (10/10), done.

In [12]:
import pandas as pd
df=pd.read_csv("/content/6156-ML-Final-Project/SAMPLE_COMBINED_TABLE_2018.csv", sep=",")

df

      YEAR  QUARTER  ...  AVG_MONTHLY_AIR_MILES_2020  MODEL_GROUP_Aircraft
0     2018        2  ...                  11633756.0               ERJ 170
1     2018        1  ...                  36689183.5                   777
2     2018        2  ...                   7636727.5                CL-600
3     2018        1  ...                   6507511.5                CL-600
4     2018        1  ...                  16813572.0                   737
...    ...      ...  ...                         ...                   ...
4995  2018        1  ...                  44768549.5               717-200
4996  2018        3  ...                  55558669.0                   737
4997  2018        4  ...                  73341633.5                   737
4998  2018        1  ...                  25162512.5                CL-600
4999  2018        1  ...                  55558669.0               ERJ 190

[5000 rows x 126 columns]

In [8]:
df.describe()

         YEAR  ...  AVG_MONTHLY_AIR_MILES_2020
count  5000.0  ...                4.988000e+03
mean   2018.0  ...                3.332921e+07
std       0.0  ...                2.478644e+07
min    2018.0  ...                3.448200e+04
25%    2018.0  ...                8.754566e+06
50%    2018.0  ...                2.516251e+07
75%    2018.0  ...                5.555867e+07
max    2018.0  ...                7.334163e+07

[8 rows x 76 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Columns: 126 entries, YEAR to MODEL_GROUP_Aircraft
dtypes: float64(49), int64(27), object(50)
memory usage: 4.8+ MB

In [13]:
df.head

<bound method NDFrame.head of       YEAR  QUARTER  ...  AVG_MONTHLY_AIR_MILES_2020  MODEL_GROUP_Aircraft
0     2018        2  ...                  11633756.0               ERJ 170
1     2018        1  ...                  36689183.5                   777
2     2018        2  ...                   7636727.5                CL-600
3     2018        1  ...                   6507511.5                CL-600
4     2018        1  ...                  16813572.0                   737
...    ...      ...  ...                         ...                   ...
4995  2018        1  ...                  44768549.5               717-200
4996  2018        3  ...                  55558669.0                   737
4997  2018        4  ...                  73341633.5                   737
4998  2018        1  ...                  25162512.5                CL-600
4999  2018        1  ...                  55558669.0               ERJ 190

[5000 rows x 126 columns]>